version: 2
updates:
  # Maintain dependencies for bun packages
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Oslo"
    open-pull-requests-limit: 5
    groups:
      dependencies:
        patterns:
          - "*"

  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Oslo"
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - "*"
